### ISSUE TITLE
no emoji

### ISSUE THREAD

**Issue by Etwhal** [Seres67/pisscord#1]
were is piss emoji point d'interrogation ?

**Comment by Seres67** [comment]
you can ask for new emojis [here](http://www.unicode.org/pending/docsubmit.html)

**Comment by Etwhal** [comment]
thx
![Toad_SMK_artwork](https://github.com/Seres67/pisscord/assets/26164997/fa4b1bc4-7413-4af2-b73f-e74d5f2fce31)
